language: python
python:
- 3.7
install:
- pip install .
script:
- pytest tests
# deploy:
#   provider: pypi
#   username: __token__
#   password:
#   on:
#     branch: master
#     repo: ihmeuw-msca/MRTool
#     tags: true